/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class julius_game_chessengine_syzygy_bridge_SyzygyBridge */

#ifndef _Included_julius_game_chessengine_syzygy_bridge_SyzygyBridge
#define _Included_julius_game_chessengine_syzygy_bridge_SyzygyBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     julius_game_chessengine_syzygy_bridge_SyzygyBridge
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_julius_game_chessengine_syzygy_bridge_SyzygyBridge_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     julius_game_chessengine_syzygy_bridge_SyzygyBridge
 * Method:    getTBLargest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_julius_game_chessengine_syzygy_bridge_SyzygyBridge_getTBLargest
  (JNIEnv *, jclass);

/*
 * Class:     julius_game_chessengine_syzygy_bridge_SyzygyBridge
 * Method:    probeWDL
 * Signature: (JJJJJJJJIZ)I
 */
JNIEXPORT jint JNICALL Java_julius_game_chessengine_syzygy_bridge_SyzygyBridge_probeWDL
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jint, jboolean);

/*
 * Class:     julius_game_chessengine_syzygy_bridge_SyzygyBridge
 * Method:    probeDTZ
 * Signature: (JJJJJJJJIIZ)I
 */
JNIEXPORT jint JNICALL Java_julius_game_chessengine_syzygy_bridge_SyzygyBridge_probeDTZ
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
